server:
  port:
    8083
spring:
  jpa:
    properties:
      hibernate:
        default_schema: spaceprint
  application:
    name: service-list
  datasource:
    url: jdbc:postgresql://localhost:5432/spaceprint

    username: postgres
    password: 88admRKS1
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
