server:
  port:
    8081

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: order-storage
  profiles:
    active: eclient, database
  config:
    import: configserver:http://localhost:8888