server:
  port:
    9091

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: services-handler
  profiles:
    active: eclient
  config:
    import: configserver:http://localhost:8888