spring:
  application:
    name: config-server
  profiles:
    active: eclient
  cloud:
    config:
      server:
        git:
          uri: /media/yuzhakovmihail/DATA/04_GeekBrains/08_backend_java_spring/printspace/config-server/src/main/resources/shop-config

server:
  port: 8888
